package com.cxxy.oem.model;

import com.cxxy.oem.model.base.BaseWorkType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkType extends BaseWorkType<WorkType> {
	public static final WorkType dao = new WorkType().dao();
}
